### PR TITLE
Front: Use CSS Variables

### LINKED ISSUE #602: Front: Fix 'System' Theme
The 'System' option for the Theme is completely broken :(

### PR DESCRIPTION
**Pull request by Arthi-chaud**
Closes #602

### CODE REVIEW

File: front/src/pages/releases/[slugOrId].tsx [hunk 1]
```diff
@@ -346,8 +346,10 @@ const ReleasePage = (props: InferSSRProps<typeof getServerSideProps>) => {
 									icon={
 										<Star1
 											size={18}
-											style={{ marginTop: -3 }}
-											color={accentColor}
+											style={{
+												marginTop: -3,
+												...accentColor,
```
Comment (Arthi-chaud) [inline front/src/pages/releases/[slugOrId].tsx:351]: Will not work
